AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  MessagesUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Description: "Message Plan for Messages Service"
      UsagePlanName: MessagesUsagePlan
      Throttle:
        BurstLimit: 50
        RateLimit: 100.0
      Quota:
        Limit: 10000
        Period: MONTH

  MessagesApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: [MessagesUsagePlan]
    Properties:
      Description: "Messages Api key for MessagesUsagePlan"
      Enabled: True
      GenerateDistinctId: True
      Name: MessagesApiKey

  MessagesUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - ServerlessRestApiProdStage
    Properties:
      UsagePlanId: !Ref MessagesUsagePlan
      KeyId: !Ref MessagesApiKey
      KeyType: API_KEY


  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_messages/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: post
            Auth:
              ApiKeyRequired: true
        GetMessages:
          Type: Api
          Properties:
            Path: /messages
            Method: get
            Auth:
              ApiKeyRequired: true

        GetMessagesByOwner:
          Type: Api
          Properties:
            Path: /messages/{owner}
            Method: get
            Auth:
              ApiKeyRequired: true

        DeleteMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: delete
            Auth:
              ApiKeyRequired: true

        UpdateMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: put
            Auth:
              ApiKeyRequired: true

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable

  MessageScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/scan_messages_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable

  MessageUserService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/scan_messages_lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "MessagesUsers"
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Messages"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "owner"
          AttributeType: "S"
        - AttributeName: "send_time"
          AttributeType: "S"
        - AttributeName: "send_year_month_day"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "owner-send_time-index"
          KeySchema:
          - AttributeName: "owner"
            KeyType: "HASH"
          - AttributeName: "send_time"
            KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: "send_year_month_day-send_time-index"
          KeySchema:
            - AttributeName: "send_year_month_day"
              KeyType: "HASH"
            - AttributeName: "send_time"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
Outputs:
  MessagesApi:
    Description: "API Gateway Message Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"