AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  product-api

  Sample SAM Template for product-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  ListItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/return_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ListItem:
          Type: Api
          Properties:
            Path: /items
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/update_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/delete_items/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
  MessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_messages/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        CreateMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: post
        GetMessages:
          Type: Api
          Properties:
            Path: /messages
            Method: get
        GetMessagesByOwner:
          Type: Api
          Properties:
            Path: /messages/{owner}
            Method: get
        DeleteMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: delete
        UpdateMessage:
          Type: Api
          Properties:
            Path: /messages
            Method: put
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Items"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Messages"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "owner"
          AttributeType: "S"
        - AttributeName: "send_time"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: "owner-send_time-index"
          KeySchema:
          - AttributeName: "owner"
            KeyType: "HASH"
          - AttributeName: "send_time"
            KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
Outputs:
  MessagesApi:
    Description: "API Gateway Message Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"